import mutations from "./mutations";
import actions from "./actions";
import getters from "./getters";

export default {
  namespaced: true,
  state() {
    return {
      playersLastFiveGames: [
        {
          name: "林志傑",
          lastFiveGames: [
            {
              gameDate: "2021/12/04",
              opponent: "台新夢想家",
              winOrLose: "敗",
              minute: "13:48",
              twoPoints: {
                fgm: 2,
                fga: 3,
              },
              threePoints: {
                fgm: 2,
                fga: 5,
              },
              freeThrow: {
                ftm: 1,
                fta: 1,
              },
              oreb: 1,
              dreb: 3,
              ast: 2,
              stl: 1,
              blk: 0,
              tov: 2,
              pf: 1,
              rpm: "+10",
            },
            {
              gameDate: "2022/01/01",
              opponent: "新竹街口攻城獅",
              winOrLose: "敗",
              minute: "24:42",
              twoPoints: {
                fgm: 1,
                fga: 6,
              },
              threePoints: {
                fgm: 3,
                fga: 5,
              },
              freeThrow: {
                ftm: 5,
                fta: 7,
              },
              oreb: 1,
              dreb: 2,
              ast: 1,
              stl: 2,
              blk: 0,
              tov: 2,
              pf: 0,
              rpm: "+8",
            },
            {
              gameDate: "2022/01/02",
              opponent: "新北國王",
              winOrLose: "勝",
              minute: "26:58",
              twoPoints: {
                fgm: 5,
                fga: 7,
              },
              threePoints: {
                fgm: 3,
                fga: 8,
              },
              freeThrow: {
                ftm: 5,
                fta: 6,
              },
              oreb: 1,
              dreb: 2,
              ast: 2,
              stl: 0,
              blk: 0,
              tov: 3,
              pf: 1,
              rpm: "+12",
            },
            {
              gameDate: "2022/01/07",
              opponent: "福爾摩沙台新夢想家",
              winOrLose: "敗",
              minute: "21:51",
              twoPoints: {
                fgm: 1,
                fga: 3,
              },
              threePoints: {
                fgm: 0,
                fga: 3,
              },
              freeThrow: {
                ftm: 0,
                fta: 2,
              },
              oreb: 0,
              dreb: 2,
              ast: 3,
              stl: 1,
              blk: 0,
              tov: 1,
              pf: 1,
              rpm: "-5",
            },
            {
              gameDate: "2022/01/09",
              opponent: "新北國王",
              winOrLose: "勝",
              minute: "17:53",
              twoPoints: {
                fgm: 1,
                fga: 1,
              },
              threePoints: {
                fgm: 0,
                fga: 3,
              },
              freeThrow: {
                ftm: 0,
                fta: 0,
              },
              oreb: 3,
              dreb: 2,
              ast: 2,
              stl: 0,
              blk: 0,
              tov: 0,
              pf: 2,
              rpm: "0",
            },
          ],
        },
        {
          name: "林書緯",
          lastFiveGames: [
            {
              gameDate: "2021/12/11",
              opponent: "新竹街口攻城獅",
              winOrLose: "勝",
              minute: "31:04",
              twoPoints: {
                fgm: 6,
                fga: 11,
              },
              threePoints: {
                fgm: 1,
                fga: 4,
              },
              freeThrow: {
                ftm: 3,
                fta: 5,
              },
              oreb: 1,
              dreb: 2,
              ast: 2,
              stl: 0,
              blk: 0,
              tov: 0,
              pf: 2,
              rpm: "+10",
            },
            {
              gameDate: "2022/01/01",
              opponent: "新竹街口攻城獅",
              winOrLose: "敗",
              minute: "32:14",
              twoPoints: {
                fgm: 8,
                fga: 10,
              },
              threePoints: {
                fgm: 1,
                fga: 3,
              },
              freeThrow: {
                ftm: 2,
                fta: 2,
              },
              oreb: 1,
              dreb: 0,
              ast: 6,
              stl: 3,
              blk: 1,
              tov: 4,
              pf: 1,
              rpm: "+8",
            },
            {
              gameDate: "2022/01/02",
              opponent: "新北國王",
              winOrLose: "勝",
              minute: "35:37",
              twoPoints: {
                fgm: 6,
                fga: 9,
              },
              threePoints: {
                fgm: 1,
                fga: 4,
              },
              freeThrow: {
                ftm: 0,
                fta: 2,
              },
              oreb: 2,
              dreb: 2,
              ast: 9,
              stl: 0,
              blk: 1,
              tov: 3,
              pf: 0,
              rpm: "+12",
            },
            {
              gameDate: "2022/01/07",
              opponent: "福爾摩沙台新夢想家",
              winOrLose: "敗",
              minute: "36:29",
              twoPoints: {
                fgm: 2,
                fga: 6,
              },
              threePoints: {
                fgm: 2,
                fga: 6,
              },
              freeThrow: {
                ftm: 2,
                fta: 2,
              },
              oreb: 4,
              dreb: 2,
              ast: 5,
              stl: 3,
              blk: 2,
              tov: 3,
              pf: 1,
              rpm: "-5",
            },
            {
              gameDate: "2022/01/09",
              opponent: "新北國王",
              winOrLose: "勝",
              minute: "31:09",
              twoPoints: {
                fgm: 3,
                fga: 5,
              },
              threePoints: {
                fgm: 2,
                fga: 6,
              },
              freeThrow: {
                ftm: 2,
                fta: 2,
              },
              oreb: 0,
              dreb: 2,
              ast: 5,
              stl: 0,
              blk: 0,
              tov: 1,
              pf: 2,
              rpm: "0",
            },
          ],
        },
        {
          name: "張宗憲",
          lastFiveGames: [
            {
              gameDate: "2021/12/11",
              opponent: "新竹街口攻城獅",
              winOrLose: "勝",
              minute: "32:42",
              twoPoints: {
                fgm: 4,
                fga: 13,
              },
              threePoints: {
                fgm: 1,
                fga: 1,
              },
              freeThrow: {
                ftm: 1,
                fta: 2,
              },
              oreb: 2,
              dreb: 2,
              ast: 3,
              stl: 2,
              blk: 0,
              tov: 1,
              pf: 1,
              rpm: "+10",
            },
            {
              gameDate: "2022/01/01",
              opponent: "新竹街口攻城獅",
              winOrLose: "敗",
              minute: "30:35",
              twoPoints: {
                fgm: 3,
                fga: 8,
              },
              threePoints: {
                fgm: 0,
                fga: 4,
              },
              freeThrow: {
                ftm: 2,
                fta: 5,
              },
              oreb: 1,
              dreb: 0,
              ast: 1,
              stl: 3,
              blk: 0,
              tov: 2,
              pf: 1,
              rpm: "+8",
            },
            {
              gameDate: "2022/01/02",
              opponent: "新北國王",
              winOrLose: "勝",
              minute: "37:42",
              twoPoints: {
                fgm: 3,
                fga: 8,
              },
              threePoints: {
                fgm: 0,
                fga: 2,
              },
              freeThrow: {
                ftm: 0,
                fta: 0,
              },
              oreb: 3,
              dreb: 2,
              ast: 4,
              stl: 1,
              blk: 1,
              tov: 1,
              pf: 3,
              rpm: "+12",
            },
            {
              gameDate: "2022/01/15",
              opponent: "新北國王",
              winOrLose: "敗",
              minute: "22:22",
              twoPoints: {
                fgm: 1,
                fga: 4,
              },
              threePoints: {
                fgm: 0,
                fga: 2,
              },
              freeThrow: {
                ftm: 0,
                fta: 0,
              },
              oreb: 0,
              dreb: 1,
              ast: 0,
              stl: 0,
              blk: 0,
              tov: 1,
              pf: 0,
              rpm: "-5",
            },
            {
              gameDate: "2022/01/16",
              opponent: "桃園領航猿",
              winOrLose: "勝",
              minute: "22:26",
              twoPoints: {
                fgm: 3,
                fga: 8,
              },
              threePoints: {
                fgm: 0,
                fga: 3,
              },
              freeThrow: {
                ftm: 0,
                fta: 0,
              },
              oreb: 1,
              dreb: 2,
              ast: 3,
              stl: 2,
              blk: 0,
              tov: 1,
              pf: 1,
              rpm: "0",
            },
          ],
        },
        {
          name: "辛特力",
          lastFiveGames: [
            {
              gameDate: "2021/12/11",
              opponent: "新竹街口攻城獅",
              winOrLose: "勝",
              minute: "45:14",
              twoPoints: {
                fgm: 10,
                fga: 23,
              },
              threePoints: {
                fgm: 4,
                fga: 10,
              },
              freeThrow: {
                ftm: 1,
                fta: 2,
              },
              oreb: 8,
              dreb: 9,
              ast: 5,
              stl: 5,
              blk: 2,
              tov: 4,
              pf: 3,
              rpm: "+10",
            },
            {
              gameDate: "2021/12/18",
              opponent: "新北國王",
              winOrLose: "敗",
              minute: "37:25",
              twoPoints: {
                fgm: 9,
                fga: 13,
              },
              threePoints: {
                fgm: 1,
                fga: 7,
              },
              freeThrow: {
                ftm: 6,
                fta: 7,
              },
              oreb: 5,
              dreb: 12,
              ast: 7,
              stl: 1,
              blk: 2,
              tov: 7,
              pf: 2,
              rpm: "+8",
            },
            {
              gameDate: "2021/12/25",
              opponent: "新竹街口攻城獅",
              winOrLose: "勝",
              minute: "43:08",
              twoPoints: {
                fgm: 2,
                fga: 7,
              },
              threePoints: {
                fgm: 3,
                fga: 8,
              },
              freeThrow: {
                ftm: 0,
                fta: 0,
              },
              oreb: 3,
              dreb: 9,
              ast: 2,
              stl: 2,
              blk: 1,
              tov: 2,
              pf: 4,
              rpm: "+12",
            },
            {
              gameDate: "2022/01/01",
              opponent: "新竹街口攻城獅",
              winOrLose: "敗",
              minute: "43:43",
              twoPoints: {
                fgm: 3,
                fga: 12,
              },
              threePoints: {
                fgm: 6,
                fga: 8,
              },
              freeThrow: {
                ftm: 10,
                fta: 10,
              },
              oreb: 4,
              dreb: 4,
              ast: 2,
              stl: 2,
              blk: 1,
              tov: 7,
              pf: 5,
              rpm: "-5",
            },
            {
              gameDate: "2022/01/02",
              opponent: "新北國王",
              winOrLose: "勝",
              minute: "27:08",
              twoPoints: {
                fgm: 4,
                fga: 9,
              },
              threePoints: {
                fgm: 3,
                fga: 6,
              },
              freeThrow: {
                ftm: 2,
                fta: 2,
              },
              oreb: 4,
              dreb: 6,
              ast: 3,
              stl: 2,
              blk: 1,
              tov: 1,
              pf: 1,
              rpm: "0",
            },
          ],
        },
        {
          name: "曾祥鈞",
          lastFiveGames: [
            {
              gameDate: "2021/12/11",
              opponent: "新竹街口攻城獅",
              winOrLose: "勝",
              minute: "21:23",
              twoPoints: {
                fgm: 0,
                fga: 3,
              },
              threePoints: {
                fgm: 0,
                fga: 1,
              },
              freeThrow: {
                ftm: 2,
                fta: 2,
              },
              oreb: 3,
              dreb: 3,
              ast: 1,
              stl: 1,
              blk: 2,
              tov: 3,
              pf: 6,
              rpm: "+10",
            },
            {
              gameDate: "2021/12/18",
              opponent: "新北國王",
              winOrLose: "敗",
              minute: "09:27",
              twoPoints: {
                fgm: 1,
                fga: 2,
              },
              threePoints: {
                fgm: 0,
                fga: 1,
              },
              freeThrow: {
                ftm: 0,
                fta: 0,
              },
              oreb: 1,
              dreb: 0,
              ast: 1,
              stl: 2,
              blk: 0,
              tov: 1,
              pf: 0,
              rpm: "+8",
            },
            {
              gameDate: "2021/12/25",
              opponent: "新竹街口攻城獅",
              winOrLose: "勝",
              minute: "09:50",
              twoPoints: {
                fgm: 1,
                fga: 1,
              },
              threePoints: {
                fgm: 0,
                fga: 0,
              },
              freeThrow: {
                ftm: 1,
                fta: 2,
              },
              oreb: 3,
              dreb: 0,
              ast: 0,
              stl: 1,
              blk: 0,
              tov: 1,
              pf: 3,
              rpm: "+12",
            },
            {
              gameDate: "2022/01/01",
              opponent: "新竹街口攻城獅",
              winOrLose: "敗",
              minute: "28:19",
              twoPoints: {
                fgm: 2,
                fga: 4,
              },
              threePoints: {
                fgm: 1,
                fga: 3,
              },
              freeThrow: {
                ftm: 1,
                fta: 2,
              },
              oreb: 4,
              dreb: 6,
              ast: 0,
              stl: 2,
              blk: 0,
              tov: 0,
              pf: 2,
              rpm: "-5",
            },
            {
              gameDate: "2022/01/07",
              opponent: "福爾摩沙台新夢想家",
              winOrLose: "敗",
              minute: "13:46",
              twoPoints: {
                fgm: 1,
                fga: 4,
              },
              threePoints: {
                fgm: 0,
                fga: 1,
              },
              freeThrow: {
                ftm: 1,
                fta: 2,
              },
              oreb: 1,
              dreb: 2,
              ast: 0,
              stl: 0,
              blk: 2,
              tov: 2,
              pf: 2,
              rpm: "0",
            },
          ],
        },
        {
          name: "塞瑟夫",
          lastFiveGames: [
            {
              gameDate: "2021/12/11",
              opponent: "新竹街口攻城獅",
              winOrLose: "勝",
              minute: "28:20",
              twoPoints: {
                fgm: 3,
                fga: 7,
              },
              threePoints: {
                fgm: 1,
                fga: 5,
              },
              freeThrow: {
                ftm: 3,
                fta: 5,
              },
              oreb: 4,
              dreb: 4,
              ast: 0,
              stl: 1,
              blk: 1,
              tov: 0,
              pf: 6,
              rpm: "+10",
            },
            {
              gameDate: "2021/12/18",
              opponent: "新北國王",
              winOrLose: "敗",
              minute: "39:58",
              twoPoints: {
                fgm: 5,
                fga: 9,
              },
              threePoints: {
                fgm: 4,
                fga: 4,
              },
              freeThrow: {
                ftm: 4,
                fta: 4,
              },
              oreb: 6,
              dreb: 5,
              ast: 0,
              stl: 0,
              blk: 0,
              tov: 4,
              pf: 2,
              rpm: "+8",
            },
            {
              gameDate: "2022/01/02",
              opponent: "新北國王",
              winOrLose: "勝",
              minute: "53:00",
              twoPoints: {
                fgm: 8,
                fga: 16,
              },
              threePoints: {
                fgm: 3,
                fga: 9,
              },
              freeThrow: {
                ftm: 2,
                fta: 4,
              },
              oreb: 8,
              dreb: 8,
              ast: 1,
              stl: 1,
              blk: 1,
              tov: 1,
              pf: 3,
              rpm: "+12",
            },
            {
              gameDate: "2022/01/07",
              opponent: "台新夢想家",
              winOrLose: "敗",
              minute: "34:42",
              twoPoints: {
                fgm: 8,
                fga: 14,
              },
              threePoints: {
                fgm: 1,
                fga: 4,
              },
              freeThrow: {
                ftm: 3,
                fta: 6,
              },
              oreb: 4,
              dreb: 6,
              ast: 2,
              stl: 1,
              blk: 3,
              tov: 5,
              pf: 1,
              rpm: "-5",
            },
            {
              gameDate: "2022/01/09",
              opponent: "新北國王",
              winOrLose: "勝",
              minute: "44:25",
              twoPoints: {
                fgm: 4,
                fga: 6,
              },
              threePoints: {
                fgm: 1,
                fga: 10,
              },
              freeThrow: {
                ftm: 1,
                fta: 2,
              },
              oreb: 4,
              dreb: 4,
              ast: 2,
              stl: 0,
              blk: 2,
              tov: 1,
              pf: 1,
              rpm: "0",
            },
          ],
        },
      ],
    };
  },
  mutations,
  actions,
  getters,
};
