import mutations from "./mutations";
import actions from "./actions";
import getters from "./getters";

export default {
  namespaced: true,
  state() {
    return {
      players: [
        {
          id: "F12",
          names: {
            chiName: "林志傑",
            engName: "Lin Chih-Chieh",
          },
          city: {
            chiCityName: "台北",
            engCityName: "Taipei",
          },
          team: {
            chiTeamName: "富邦勇士",
            engTeamName: "Fubon",
          },
          height: 192,
          weight: 92,
          age: 40,
          experience: 18,
          birthday: "1982-06-11",
          country: "台灣",
          lastAttended: "中國文化大學",
          position: "後衛",
          number: "12",
          playedGames: 24,
          points: 258,
          rebounds: 120,
          assists: 76,
          turnover: 49,
          steal: 20,
          block: 2,
          achievements: [
            "2003-2009 台灣啤酒籃球隊– SBL 超級籃球聯賽",
            "2009-2019 浙江廣廈籃球隊– CBA 中國男子籃球職業聯賽",
            "2019-至今 臺北富邦勇士籃球隊– ABL東南亞職業籃球聯賽",
            "2020-至今 臺北富邦勇士籃球隊– P.LEAGUE+",
            "2x SBL 總冠軍 （2007, 2008）",
            "2x SBL 總冠軍 MVP （2007, 2008）",
            "SBL MVP 年度最有價值球員 （2007）",
            "7x CBA 全明星 （2010-2011, 2013-2017）",
            "2x SBL 年度得分王 （2003, 2004）",
            "4x SBL 年度第一隊 （2004, 2005, 2006, 2007）",
            "2x CBA 技巧挑戰賽冠軍 （2010, 2011）",
            "P.LEAGUE+ 總冠軍 （2021）",
            "P.LEAGUE+ 年度人氣王 （2021）",
            "中華台北男子籃球國家代表隊 （2003-2015）",
          ],
        },
        {
          id: "F1",
          names: {
            chiName: "林書緯",
            engName: "Lin Joseph Shu-Wei",
          },
          city: {
            chiCityName: "台北",
            engCityName: "Taipei",
          },
          team: {
            chiTeamName: "富邦勇士",
            engTeamName: "Fubon",
          },
          height: 182,
          weight: 69,
          age: 29,
          experience: 7,
          birthday: "1992-06-21",
          country: "美國",
          lastAttended: "Hamilton College",
          position: "後衛",
          number: "1",
          playedGames: 27,
          points: 280,
          rebounds: 84,
          assists: 104,
          turnover: 49,
          steal: 39,
          block: 9,
          achievements: [
            "2015-2019 富邦勇士籃球隊– SBL超級籃球聯賽",
            "2019-至今 臺北富邦勇士籃球隊– ABL東南亞職業籃球聯賽",
            "2020-至今 臺北富邦勇士籃球隊– P.LEAGUE+",
            "SBL總冠軍 （2019）",
            "SBL年度最佳新人 （2016）",
            "SBL年度第一隊（2016）",
            "SBL年度助攻王 （2016）",
            "SBL明星賽技術挑戰賽冠軍 （2017）",
            "P.LEAGUE+總冠軍 （2021）",
          ],
        },
        {
          id: "F3",
          names: {
            chiName: "張宗憲",
            engName: "Chang Tsung-Hsien",
          },
          city: {
            chiCityName: "台北",
            engCityName: "Taipei",
          },
          team: {
            chiTeamName: "富邦勇士",
            engTeamName: "Fubon",
          },
          height: 192,
          weight: 88,
          age: 33,
          experience: 7,
          birthday: "1988-12-27",
          country: "台灣",
          lastAttended: "Brigham Young University-Hawaii",
          position: "前鋒",
          number: "3",
          playedGames: 32,
          points: 464,
          rebounds: 80,
          assists: 96,
          turnover: 69,
          steal: 56,
          block: 4,
          achievements: [
            "2013-2015 四川金強– CBA 中國男子籃球職業聯賽",
            "2015 起亞隊– PBA 菲律賓職業籃球聯賽",
            "2016-2019 富邦勇士籃球隊– SBL 超級籃球聯賽",
            "2019-2020 寶島夢想家籃球隊– ABL 東南亞職業籃球聯賽",
            "2020-至今 臺北富邦勇士籃球隊– P.LEAGUE+",
            "SBL 總冠軍 （2019）",
            "SBL 全明星 （2018）",
            "SBL 年度第一隊（2018）",
            "P.LEAGUE+總冠軍 （2021）",
            "P.LEAGUE+年度最有價值球員 MVP （2021）",
            "P.LEAGUE+年度第一隊 （2021）",
            "P.LEAGUE+年度防守第一隊 （2021）",
            "中華台北男子籃球國家代表隊 （2009, 2011 - 2016）",
          ],
        },
        {
          id: "F17",
          names: {
            chiName: "辛特力",
            engName: "Michael Singletary",
          },
          city: {
            chiCityName: "台北",
            engCityName: "Taipei",
          },
          team: {
            chiTeamName: "富邦勇士",
            engTeamName: "Fubon",
          },
          height: 198,
          weight: 103,
          age: 33,
          experience: 11,
          birthday: "1988-09-19",
          country: "美國",
          lastAttended: "Texas Tech University",
          position: "前鋒",
          number: "17",
          playedGames: 26,
          points: 569,
          rebounds: 286,
          assists: 96,
          turnover: 87,
          steal: 38,
          block: 11,
          achievements: [
            "2011 Verviers-Pepinster– Belgian First Division",
            "2012–2013 Rio Grande Valley Vipers– NBA 發展聯盟",
            "2013 Erie BayHawks– NBA 發展聯盟",
            "2013 Barako Bull Energy Cola– Philippine Basketball Association",
            "2014-2015 Basket Ravenna Piero Manetti– Serie A2 Basket",
            "2016 San Miguel Beermen– Philippine Basketball Association",
            "2016–2020 Mono Vampire泰國吸血鬼– ABL 東南亞職業籃球聯賽",
            "2020-至今 臺北富邦勇士籃球隊 – P.LEAGUE+",
            "P.LEAGUE+總冠軍 （2021）",
            "P.LEAGUE+總冠軍 MVP （2021）",
          ],
        },
        {
          id: "F21",
          names: {
            chiName: "曾祥鈞",
            engName: "Tseng Hsiang-Chun",
          },
          city: {
            chiCityName: "台北",
            engCityName: "Taipei",
          },
          team: {
            chiTeamName: "富邦勇士",
            engTeamName: "Fubon",
          },
          height: 205,
          weight: 95,
          age: 23,
          experience: 2,
          birthday: "1998-08-08",
          country: "台灣",
          lastAttended: "輔仁大學",
          position: "中鋒",
          number: "21",
          playedGames: 34,
          points: 181,
          rebounds: 179,
          assists: 25,
          turnover: 22,
          steal: 17,
          block: 28,
          achievements: [
            "2016-2020 UBA 輔仁大學籃球隊",
            "2020-至今 臺北富邦勇士籃球隊 – P.LEAGUE+",
            "106 學年度 UBA 阻攻王",
            "107 學年度 UBA 籃板王、阻攻王",
            "108 學年度 UBA 得分王",
            "P.LEAGUE+ 總冠軍 （2021）",
            "中華台北男子籃球國家代表隊 （2017 - 2019)",
          ],
        },
        {
          id: "F32",
          names: {
            chiName: "塞瑟夫",
            engName: "Ihor Zaytsev",
          },
          city: {
            chiCityName: "台北",
            engCityName: "Taipei",
          },
          team: {
            chiTeamName: "富邦勇士",
            engTeamName: "Fubon",
          },
          height: 211,
          weight: 110,
          age: 32,
          experience: 14,
          birthday: "1989-05-11",
          country: "烏克蘭",
          lastAttended: "",
          position: "中鋒",
          number: "32",
          playedGames: 27,
          points: 481,
          rebounds: 328,
          assists: 61,
          turnover: 65,
          steal: 24,
          block: 26,
          achievements: [
            "2008-2011 SC Kryvba– Ukrainian Basketball SuperLeague",
            "2011-2014 BC Azovmash– Ukrainian Basketball SuperLeague",
            "2014-2015 BC Khimik– Ukrainian Basketball SuperLeague",
            "2015 Petrochimi Bandar Imam BC– Iranian Super League",
            "2015-2016 Rosa Radom– Polish Basketball League",
            "2016 Basket Zielona Góra– Polish Basketball League",
            "2016-2017 Bàsquet Manresa– Liga ACB西班牙籃球甲級聯賽",
            "2017-2018 Rosa Radom– Polish Basketball League",
            "2018-2020台灣啤酒籃球隊– SBL 超級籃球聯賽",
            "2019 重慶華熙國際隊– NBL 全國男子籃球聯賽",
            "2020-至今 臺北富邦勇士籃球隊 – P.LEAGUE+",
            "Ukrainian Basketball SuperLeague總冠軍（2014-2015）",
            "Polish Basketball League 總冠軍（2015-2016）",
            "SBL年度最佳洋將（2019）",
            "SBL年度第一隊（2019）",
            "SBL年度最佳前場防守球員（2020）",
            "SBL總冠軍（2020）",
            "P.LEAGUE+ 總冠軍（2021）",
            "P.LEAGUE+ 年度洋將（2021）",
            "P.LEAGUE+ 年度第一隊（2021）",
          ],
        },
      ],
    };
  },
  mutations,
  actions,
  getters,
};
