import mutations from "./mutations";
import actions from "./actions";
import getters from "./getters";

export default {
  namespaced: true,
  state() {
    return {
      players: [
        {
          id: "F12",
          names: {
            chiName: "林志傑",
            engName: "Lin Chih-Chieh",
          },
          city: {
            chiCityName: "台北",
            engCityName: "Taipei",
          },
          team: {
            chiTeamName: "富邦勇士",
            engTeamName: "Fubon",
          },
          height: 192,
          weight: 92,
          age: 40,
          experience: 18,
          birthday: "1982-06-11",
          country: "台灣",
          lastAttended: "中國文化大學",
          position: "後衛",
          number: "12",
          playedGames: 24,
          points: 258,
          rebounds: 120,
          assists: 76,
          turnover: 49,
          steal: 20,
          block: 2,
        },
        {
          id: "F1",
          names: {
            chiName: "林書緯",
            engName: "Lin Joseph Shu-Wei",
          },
          city: {
            chiCityName: "台北",
            engCityName: "Taipei",
          },
          team: {
            chiTeamName: "富邦勇士",
            engTeamName: "Fubon",
          },
          height: 182,
          weight: 69,
          age: 29,
          experience: 7,
          birthday: "1992-06-21",
          country: "美國",
          lastAttended: "Hamilton College",
          position: "後衛",
          number: "1",
          playedGames: 27,
          points: 280,
          rebounds: 84,
          assists: 104,
          turnover: 49,
          steal: 39,
          block: 9,
        },
        {
          id: "F3",
          names: {
            chiName: "張宗憲",
            engName: "Chang Tsung-Hsien",
          },
          city: {
            chiCityName: "台北",
            engCityName: "Taipei",
          },
          team: {
            chiTeamName: "富邦勇士",
            engTeamName: "Fubon",
          },
          height: 192,
          weight: 88,
          age: 33,
          experience: 7,
          birthday: "1988-12-27",
          country: "台灣",
          lastAttended: "Brigham Young University-Hawaii",
          position: "前鋒",
          number: "3",
          playedGames: 32,
          points: 464,
          rebounds: 80,
          assists: 96,
          turnover: 69,
          steal: 56,
          block: 4,
        },
        {
          id: "F17",
          names: {
            chiName: "辛特力",
            engName: "Michael Singletary",
          },
          city: {
            chiCityName: "台北",
            engCityName: "Taipei",
          },
          team: {
            chiTeamName: "富邦勇士",
            engTeamName: "Fubon",
          },
          height: 198,
          weight: 103,
          age: 33,
          experience: 11,
          birthday: "1988-09-19",
          country: "美國",
          lastAttended: "Texas Tech University",
          position: "前鋒",
          number: "17",
          playedGames: 26,
          points: 569,
          rebounds: 286,
          assists: 96,
          turnover: 87,
          steal: 38,
          block: 11,
        },
        {
          id: "F21",
          names: {
            chiName: "曾祥鈞",
            engName: "Tseng Hsiang-Chun",
          },
          city: {
            chiCityName: "台北",
            engCityName: "Taipei",
          },
          team: {
            chiTeamName: "富邦勇士",
            engTeamName: "Fubon",
          },
          height: 205,
          weight: 95,
          age: 23,
          experience: 2,
          birthday: "1998-08-08",
          country: "台灣",
          lastAttended: "輔仁大學",
          position: "中鋒",
          number: "21",
          playedGames: 34,
          points: 181,
          rebounds: 179,
          assists: 25,
          turnover: 22,
          steal: 17,
          block: 28,
        },
        {
          id: "F32",
          names: {
            chiName: "塞瑟夫",
            engName: "Ihor Zaytsev",
          },
          city: {
            chiCityName: "台北",
            engCityName: "Taipei",
          },
          team: {
            chiTeamName: "富邦勇士",
            engTeamName: "Fubon",
          },
          height: 211,
          weight: 110,
          age: 32,
          experience: 14,
          birthday: "1989-05-11",
          country: "烏克蘭",
          lastAttended: "",
          position: "中鋒",
          number: "32",
          playedGames: 27,
          points: 481,
          rebounds: 328,
          assists: 61,
          turnover: 65,
          steal: 24,
          block: 26,
        },
      ],
    };
  },
  mutations,
  actions,
  getters,
};
